Pass only prefixed attributes to filters
ansible-collections/community.digitalocean pull request #102
Opened 2021-05-27 23:44 UTC by maxtruxa

##### SUMMARY
This PR is mutually exclusive with #103.

In contrast to the jinja expressions in `compose`, `groups` and `keyed_groups`, `filters` was given *all* droplet attributes without a prefix. My bad for not catching that.

Note that this will break anyone who started using this feature since the release of version 1.5.0. If that is a no-go, I can amend the PR to keep the previous inconsistent behavior as well.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
Inventory plugin

##### ADDITIONAL INFORMATION
Before:
```yml
plugin: community.digitalocean.digitalocean
attributes:
  - tags
filters:
  - '"test" in tags'
```
or even without the attributes:
```yml
plugin: community.digitalocean.digitalocean
filters:
  - '"test" in tags'
```

After:
```yml
plugin: community.digitalocean.digitalocean
attributes:
  - tags
filters:
  - '"test" in do_tags'
```

2021-06-05 19:47 UTC, tadeboro requested changes
I think this PR is superior compared to #103 because it preserves the consistency of behavior. And although this is indeed an API break, I would say that the original behavior was flawed, and thus this is a fix that sets things straight. Plus, the Ansible PyPI package did not include the "broken" version of the plugin yet, so not many users were exposed to it.

But this PR does need a documentation fragment that describes the change, this is why I am requesting changes in my review.

2021-06-08 18:44 UTC, maxtruxa commented
@tadeboro Thanks for the feedback! I added the missing changelog fragment.

2021-06-08 20:10 UTC, tadeboro approved these changes

2021-06-10 12:38 UTC, mamercad approved these changes
Thank you very much for this, want to close #103?

2021-06-10 12:40 UTC, merged

2021-06-10 13:02 UTC, maxtruxa commented
Closed #103. Thank you!