Add project module
ansible-collections/community.digitalocean pull request #104
Opened 2021-05-31 01:49 UTC by tylerauerbeck

##### SUMMARY
Begins to address #71 by adding the ability to manage a DO project

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
digital_ocean_project 

##### ADDITIONAL INFORMATION
This adds the ability to manage a digital ocean project via this collection.

2021-06-05 12:47 UTC, mamercad commented on plugins/modules/digital_ocean_project.py
> +- community.digitlocean.digital_ocean_project:
Small typo in this example "digitlocean".

2021-06-05 12:48 UTC, mamercad commented on tests/integration/targets/digital_ocean_project/tasks/main.yml
> +    - name: Verify Droplet is absent
Fixup name to say "Project" not "Droplet".

2021-06-05 12:48 UTC, mamercad commented on tests/integration/targets/digital_ocean_project/tasks/main.yml
> +    - name: Verify Droplet is present (from present)
"Project"

2021-06-05 12:48 UTC, mamercad commented on tests/integration/targets/digital_ocean_project/tasks/main.yml
> +    - name: Verify Droplet is present (from existing)
"Project"

2021-06-05 12:49 UTC, mamercad requested changes
Very nice, just small things to fix, thank you!

2021-06-05 15:21 UTC, tylerauerbeck commented
Good catch! These should be fixed up now.

2021-06-06 14:26 UTC, mamercad approved these changes
LGTM, thanks much!

2021-06-06 14:26 UTC, merged