digital_ocean_firewall: new module
ansible-collections/community.digitalocean pull request #16
Opened 2020-08-11 22:59 UTC by lucasbasquerotto

##### SUMMARY
This PR has the new module to create and update Digital Ocean Firewall rules.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
digital_ocean_firewall

##### ADDITIONAL INFORMATION
Related: https://github.com/ansible/ansible/pull/46618#issuecomment-671323757

2020-08-12 00:12 UTC, lucasbasquerotto commented
I documented a list of objects like:

```
  inbound_rules:
    description:
      - Firewall rules specifically targeting inbound network traffic into Digital Ocean
    required: true
    type: list
    suboptions:
      protocol:
      ...
```

and specified as:

`inbound_rules=dict(type='list', elements='dict', options=inbound_spec, required=True)`

but got `ERROR: plugins/modules/digital_ocean_firewall.py:0:0: doc-elements-mismatch: Argument 'inbound_rules' in argument_spec specifies elements as dict,but elements is not documented`

The same happened with outbound rules. I don't know what need to be changed.

I also defined `addresses` as `addresses=dict(type='list', required=False)`, but got:

`ERROR: plugins/modules/digital_ocean_firewall.py:0:0: parameter-list-no-elements: Argument 'addresses' in argument_spec found in inbound_rules -> sources defines type as list but elements is not defined`

Then I specified as `addresses=dict(type='list', elements='str', required=False)` (with `elements='str')`, but got:

`ERROR: plugins/modules/digital_ocean_firewall.py:0:0: doc-elements-mismatch: Argument 'addresses' in argument_spec found in inbound_rules -> sources specifies elements as str,but elements is not documented`

So I don't know exactly what is the problem here. 

If I understood correctly, if `elements `is a complex object like a dict or a list, the documentation need the `suboptions`. If it's a string the options isn't needed in the spec (and the suboptions isn't needed in the documentation), like [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/iptables.py). I looked at https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#options and don't know exatly what needs to be done. Furthermore, it documents how to make the spec, and not the documentation (based on the spec).

2020-09-30 15:14 UTC, zetoph commented
I don't have a lot of experiences with writing Ansible modules but could it be that you have to document `inbound_rules.sources.addresses.elements` explicitly?
Somewhere along those lines:
```
  inbound_rules:
    description:
      - Firewall rules specifically targeting inbound network traffic into Digital Ocean
    required: true
    type: list
    suboptions:
      protocol:
        description:
          - Network protocol to be accepted.
        required: false
        default: tcp
        choices: ['udp', 'tcp', 'icmp']
      ports:
        description:
          - The ports on which traffic will be allowed, single, range, or all
        required: true
      sources:
        description:
          - Dictionary of locations from which inbound traffic will be accepted
        required: true
        suboptions:
          addresses:
            description:
              - List of strings containing the IPv4 addresses, IPv6 addresses, IPv4 CIDRs,
                and/or IPv6 CIDRs to which the firewall will allow traffic
            required: false
            suboptions:
              elements:
                description:
                  - IPv4 or IPv6 address in CIDR notation.
                type: str
```
And then accordingly for the other 27 issues.

2020-09-30 22:12 UTC, lucasbasquerotto commented
@zetoph It seems that elements have to be defined in the docs. It seems that this is recent, and I found a file that have an example (https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/command.py) and the commit that added it in this file (and several others) is from 8 days ago (https://github.com/ansible/ansible/commit/3e9943bc5e7a9cd393757aa8100d7fed80bd316e).

So it seems that this rule is not well documented, but based on that I added `elements: [element_type]` in the docs when type is `list` or `dict`, like:

```yaml
droplet_ids:
  type: list
  elements: str
  description:
    - List of droplet ids to be assigned to the firewall
  required: false
```
and

```yaml
inbound_rules:
  type: list
  elements: dict
  description:
    - Firewall rules specifically targeting inbound network traffic into Digital Ocean
  required: true
  suboptions:
    protocol:
      ...
```

2020-10-09 22:07 UTC, mamercad requested changes

2020-10-09 22:07 UTC, mamercad commented on plugins/modules/digital_ocean_firewall.py
> +    - This module can be used to add or remove firewalls on the Digital Ocean cloud platform.
Here also.

2020-10-09 22:07 UTC, mamercad commented on plugins/modules/digital_ocean_firewall.py
> +      - Firewall rules specifically targeting inbound network traffic into Digital Ocean
And here.

2020-10-09 22:07 UTC, mamercad commented on plugins/modules/digital_ocean_firewall.py
> +      - Firewall rules specifically targeting outbound network traffic from Digital Ocean
As well as here.

2020-10-09 22:07 UTC, mamercad commented on plugins/modules/digital_ocean_firewall.py
> +            self.module.fail_json(msg="Failed to retrieve firewalls from Digital Ocean")
And here please.

2020-10-12 16:36 UTC, lucasbasquerotto commented on plugins/modules/digital_ocean_firewall.py
> +short_description: Manage cloud firewalls within Digital Ocean
Done

2020-10-12 17:34 UTC, mamercad submitted a review, later dismissed

2021-03-25 21:28 UTC, mamercad submitted a review, later dismissed
I've updated the name to meet DO's firewall naming requirements.

2021-03-26 11:45 UTC, lucasbasquerotto commented
@mamercad It's only now that I saw the other places you posted to fix the names, weird, because I think I didn't receive notifications after the 1st case, which is the reason I haven't fixed them previously, only now I was notificated with your comment. Thanks for the changes!

2021-03-26 12:26 UTC, mamercad commented
> @mamercad It's only now that I saw the other places you posted to fix the names, weird, because I think I didn't receive notifications after the 1st case, which is the reason I haven't fixed them previously, only now I was notificated with your comment. Thanks for the changes!

No worries, thank *you*.

2021-03-31 01:05 UTC, mamercad commented
@lucasbasquerotto Mind adding a quick [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment)?

I think it'll look something like this:

```yaml
minor_changes:
  - digital_ocean_firewall - Adding a new module for DigitalOcean firewalls
```

2021-03-31 20:38 UTC, mamercad approved these changes
LGTM

2021-03-31 20:40 UTC, merged

2021-03-31 20:40 UTC, mamercad commented
@lucasbasquerotto Thanks very much for this contribution! 👋