make droplet firewall adding/removing report changed properly
ansible-collections/community.digitalocean pull request #219
Opened 2022-02-02 15:08 UTC by magicrobotmonkey

##### SUMMARY
When using the droplet module, the presence of the `firewalls` argument causes the module to always report changed=True, even when no changes were necessary/made. This patch causes it to track if the droplet needed to be added or removed from any firewalls and reports changed appropriately. 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
digital_ocean_droplet

##### ADDITIONAL INFORMATION
Running the droplet module even with an empty list passed to firewalls returns changed=true.

```
- name: Show a droplet always changing just because firewall is present
  community.digitalocean.digital_ocean_droplet:
    state: present
    oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
    id: 123
    name: mydroplet
    size: s-1vcpu-1gb
    region: sfo3
    image: ubuntu-20-04-x64
    firewall: []
    wait_timeout: 500
```

2022-02-02 23:02 UTC, mamercad commented
The output is a bit overwhelming (for the integration tests), but, I think that this is what's failing:

```
TASK [digital_ocean_droplet : Verify things were changed for firewall removal] ***
task path: /root/ansible_collections/community/digitalocean/tests/output/.tmp/integration/digital_ocean_droplet-3fprxayv-ÅÑŚÌβŁÈ/tests/integration/targets/digital_ocean_droplet/tasks/main.yml:452
fatal: [testhost]: FAILED! => {
    "assertion": "firewall_droplet_removal.changed is true",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}
```

2022-02-03 12:55 UTC, magicrobotmonkey commented
crossed wires moving my patch to my working dir... fix incoming

2022-02-03 23:40 UTC, magicrobotmonkey commented
I can't tell what failed this time, I don't even see the firewall tests running...?

2022-02-05 00:03 UTC, mamercad commented
You're good, it passed.

2022-02-05 01:15 UTC, mamercad requested changes
Thanks for the contribution @magicrobotmonkey; please add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#changelog-fragment-entry-format).

2022-02-15 12:51 UTC, mamercad commented on changelogs/fragments/219-droplet-firewall-changed-reporting.yaml
> +  - digital_ocean_droplet - fix reporting of changed state when ``firewall`` argument is present
This is missing a reference at the end, e.g., "... is present (link to this PR)." -- please look at the [documentation](https://docs.ansible.com/ansible/latest/community/development_process.html#changelog-fragment-entry-format).

2022-02-15 12:51 UTC, mamercad requested changes
Left a comment on the changelog fragment.

2022-02-15 21:15 UTC, mamercad requested changes

2022-02-15 21:15 UTC, mamercad commented on changelogs/fragments/219-droplet-firewall-changed-reporting.yaml
> +  - digital_ocean_droplet - fix reporting of changed state when ``firewall`` argument is present (https://github.com/ansible-collections/community.digitalocean/pull/219)
Nit: these need to end with periods `.`

2022-02-16 00:38 UTC, mamercad approved these changes
Thanks for fixing this! 🚀

2022-02-16 00:43 UTC, merged