Allow deleting droplet by id
ansible-collections/community.digitalocean pull request #261
Opened 2022-06-01 04:39 UTC by coreywright

##### SUMMARY
For droplet deletion, #184 required `name` and `unique_name` and
verified `unique_name` is true, to the exclusion of `id`.

Remove requirement from `required_if` as it cannot enforce the logic
`id or (name and unique_name)` and modify the verification of
`unique_name` to include `id` (and don't worry about `name` because
either it or `id` are already required elsewhere).

Fixes #260.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
digital_ocean_droplet

2022-06-01 18:22 UTC, coreywright commented
another force push because i didn't pay enough attention to the black finding, ie hanging comma.

2022-06-02 23:37 UTC, mamercad requested changes
Sweet; could you create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). Also, if you don't mind, and integration test which deletes by Droplet ID and verifies the deletion?

2022-06-06 22:10 UTC, coreywright commented
force push commit modifying integration tests to verify deleting by:
* id only
* unique name and id
* unique name only

2022-06-06 22:25 UTC, coreywright commented
force push adding changelog fragment.

2022-06-08 00:56 UTC, mamercad commented
Sweet; I've got your branch checked out (the integration tests are rocky right now), and I'm running the Droplet tests locally.

2022-06-08 01:04 UTC, mamercad commented
> Sweet; I've got your branch checked out (the integration tests are rocky right now), and I'm running the Droplet tests locally.

The Droplet tests passed 🎉

2022-06-08 01:04 UTC, mamercad approved these changes
🚢

2022-06-08 01:05 UTC, merged