Get updated droplet by id during create wait
ansible-collections/community.digitalocean pull request #265
Opened 2022-06-02 17:40 UTC by coreywright

##### SUMMARY
When updating droplet info while waiting after creation, instead of
using `get_droplet()` and being dependent upon the optional
`unique_name` feature, use `get_by_id()` with the droplet's ID which
we definitively have having just created the droplet.

Fixes #220.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
digital_ocean_droplet

2022-06-06 20:12 UTC, coreywright commented
force pushed to modify integration test to verifying `droplet.networks.v4 != []`.

2022-06-06 22:34 UTC, coreywright commented
force push commit adding changelog fragment.

2022-06-08 01:08 UTC, mamercad requested changes
Couple of small language changes please!

2022-06-08 01:08 UTC, mamercad commented on changelogs/265-get_updated_droplet_info_on_create_wait_by_id.yaml
> +bugfix:
Please change to `bugfixes`

2022-06-08 01:08 UTC, mamercad commented on changelogs/265-get_updated_droplet_info_on_create_wait_by_id.yaml
> +  - digital_ocean_droplet - fix regression where droplet info (eg networking)
Please change "eg" into "for example," and move the period after `true` to the very end of the line (after the final parenthesis).

2022-06-08 11:11 UTC, coreywright commented
force push updated commit which:
* moves changelog fragment to proper directory (changlelogs → changelogs/fragments)
* `bugfix:` → `bugfixes:`
* `eg` → `for example`
* moves period to very end, past issue URL.

2022-06-09 01:41 UTC, mamercad approved these changes
Thanks for this!

2022-06-09 01:42 UTC, merged