Actually activate inventory caching
ansible-collections/community.digitalocean pull request #97
Opened 2021-05-23 20:50 UTC by tadeboro

##### SUMMARY

The inventory plugin advertises support for caching, but the implementation was missing the required pieces to make it work properly.

This commit split the inventory construction into two stages. The first stage is responsible for fetching remote data (interacting with the DigitalOcean's API). The second stage extracts the relevant data from the API responses and populated the inventory.

Caching support then came almost for free. All we had to do is only fetch data if:

 1. User does not want to use cache at all.
 2. User does use cache and wants data refreshed.
 3. User does use cache, but the cache is empty.

Some additional logic makes sure we write the data to cache if data refresh is requested, but nothing too complex.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
`community.digitalocean.digitalocean` inventory plugin

2021-05-23 21:18 UTC, tadeboro commented
Not sure what codecov did here, but those numbers are definitely broken. It looks like we are comparing full coverage with partial coverage (only lines that I changed), but since I do not use codecov personally, I have no experience with these things.

2021-05-24 23:21 UTC, mamercad commented
@gundalow Can you help us with the failing `codecov/patch` test?

2021-05-24 23:44 UTC, mamercad approved these changes
Thanks for fixing this, LGTM:

```bash
❯ grep cache digitalocean.yml
cache: yes
cache_plugin: jsonfile
cache_timeout: 300
cache_connection: /tmp/do_inventory
cache_prefix: do_

❯ head /tmp/do_inventory/do_community.digitalocean.digitalocean_bccfds_7fdd2
[
    {
        "backup_ids": [],
        "created_at": "2021-05-24T23:40:20Z",
        "disk": 25,
        "features": [
            "private_networking"
        ],
        "id": 247480313,
        "image": {
```

2021-05-25 02:36 UTC, mamercad commented
@tadeboro Want to add a quick changelog fragment?

2021-05-25 02:49 UTC, mamercad requested changes
Changelog fragment please.

2021-05-25 17:30 UTC, tadeboro commented
@mamercad I wanted to add a changelog fragment once I knew the PR number, but then the code coverage distracted me ;)

2021-05-25 18:06 UTC, gundalow commented
> @gundalow Can you help us with the failing `codecov/patch` test?

Could you try changing `codecov.yml` to the following:

```yaml
coverage:
  status:
    project:
      default:
        informational: true # Don't fail CI if percentage drops
    patch:
      default:
        informational: true # Don't fail CI if percentage drops

# Don't count lines of code in these directories
ignore:
    - tests
fixes:
  - "ansible_collections/community/digitalocean/::"
```

2021-05-31 11:02 UTC, tadeboro commented
I rebased the changes onto the ` main` branch. The codecov is still complaining because the updated lines are not covered by unit tests. And while I can add tests to cover them just to make codecov happy, I would rather not. Why? Because I will need to mock 90% of the inventory plugin functionality just to cover three if statements. And such tests (tests that do not actually test any surrounding code) are worthless in the long run since they do not adapt to the changes in the core.

2021-06-01 11:39 UTC, mamercad approved these changes
Thanks for fixing this!

2021-06-01 11:41 UTC, merged